# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(640, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/Images/d-element-blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(18, 120, 601, 109))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.COMPort = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.COMPort.setObjectName("COMPort")
        self.gridLayout_2.addWidget(self.COMPort, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.pathEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.pathEdit.setText("")
        self.pathEdit.setObjectName("pathEdit")
        self.gridLayout_2.addWidget(self.pathEdit, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.conIP = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.conIP.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.conIP.setFont(font)
        self.conIP.setObjectName("conIP")
        self.gridLayout_2.addWidget(self.conIP, 2, 1, 1, 1)
        self.PCIP = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.PCIP.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.PCIP.setFont(font)
        self.PCIP.setObjectName("PCIP")
        self.gridLayout_2.addWidget(self.PCIP, 3, 1, 1, 1)
        self.about = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.about.setMinimumSize(QtCore.QSize(85, 0))
        self.about.setObjectName("about")
        self.gridLayout_2.addWidget(self.about, 3, 4, 1, 1)
        self.fileSelect = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.fileSelect.setMaximumSize(QtCore.QSize(85, 16777215))
        self.fileSelect.setDefault(False)
        self.fileSelect.setFlat(False)
        self.fileSelect.setObjectName("fileSelect")
        self.gridLayout_2.addWidget(self.fileSelect, 0, 2, 1, 1)
        self.goButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.goButton.setEnabled(True)
        self.goButton.setMinimumSize(QtCore.QSize(85, 0))
        self.goButton.setObjectName("goButton")
        self.gridLayout_2.addWidget(self.goButton, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(210, 15, 220, 90))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Images/Images/duagon-logo-seethru.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.actionrunStuff = QtWidgets.QAction(Dialog)
        self.actionrunStuff.setObjectName("actionrunStuff")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pathEdit, self.fileSelect)
        Dialog.setTabOrder(self.fileSelect, self.COMPort)
        Dialog.setTabOrder(self.COMPort, self.conIP)
        Dialog.setTabOrder(self.conIP, self.PCIP)
        Dialog.setTabOrder(self.PCIP, self.goButton)
        Dialog.setTabOrder(self.goButton, self.about)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "OEM PC2/PC3 Linux Kernel Update Utility 1.0"))
        self.label_4.setText(_translate("Dialog", "Controller IP address:"))
        self.label_3.setText(_translate("Dialog", "RS232 serial port:"))
        self.label_7.setText(_translate("Dialog", "Linux kernel location:"))
        self.label_5.setText(_translate("Dialog", "PC IP address:"))
        self.about.setText(_translate("Dialog", "About"))
        self.fileSelect.setText(_translate("Dialog", "Select directory"))
        self.goButton.setText(_translate("Dialog", "Load kernel"))
        self.actionrunStuff.setText(_translate("Dialog", "runStuff"))
import ImageSources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
